# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user-login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(362, 461)
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(10, 10, 341, 440))
        self.widget.setStyleSheet("background-color: rgba(255, 255, 255, 255);\n"
                "border-radius: 20px;\n"
                "border: 1px solid black;")
        self.widget.setObjectName("widget")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 170, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("background-color: #fafafa;\n"
                "padding-left: 20px;")
        self.lineEdit.setMaxLength(5)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 240, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: #fafafa;\n"
                "padding-left: 20px;")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setGeometry(QtCore.QRect(40, 340, 261, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton#pushButton{\n"
                "background-color: #fa862d;\n"
                "color: rgba(255, 255, 255, 255);\n"
                "    font: 57 10pt \"Dubai Medium\";\n"
                "    font: 14pt \"MS Shell Dlg 2\";\n"
                "}\n"
                "QPushButton#pushButton:pressed{\n"
                "background-color: #cc2705;\n"
                "padding-left: 3px;\n"
                "padding-top: 3px;\n"
                "color: rgba(255, 255, 255, 255);\n"
                "    font: 57 10pt \"Dubai Medium\";\n"
                "    font: 14pt \"MS Shell Dlg 2\";\n"
                "}\n"
                "QPushButton#pushButton:hover{\n"
                "background-color: #cc9805;\n"
                "}")
        self.pushButton.setIconSize(QtCore.QSize(16, 16))
        self.pushButton.setAutoDefault(False)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(130, 40, 91, 111))
        font = QtGui.QFont()
        font.setPointSize(65)
        self.label.setFont(font)
        self.label.setStyleSheet("border: 0px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(90, 390, 241, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:0px;\n"
                "color:grey;\n"
                "QLabel#hover{\n"
                "color: black;\n"
                "}")
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Performance Tracker Login"))
        self.lineEdit.setPlaceholderText(_translate("Form", "Username"))
        self.lineEdit_2.setPlaceholderText(_translate("Form", "Password"))
        self.pushButton.setText(_translate("Form", "L o g  I n"))
        self.label.setText(_translate("Form", ""))
        self.label_2.setText(_translate("Form", "Forgot our username or password?"))

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())